### ISSUE TITLE
UserService scope

### ISSUE THREAD

**Issue by idrm** [MatthewVita/spring-boot-private-chat#2]
If I'm not mistaken UserService has a singleton scope. Won't that introduce a racing condition into the currentUser property?

**Comment by MatthewVita** [comment]
Hi,

This is something I have had on my personal todo list for a while. I will now move it up in priority since someone else has noticed it!

I've primarily used this repo as a learning project for websockets and have only ran it on my PC. However, having `currentUser` state in the singleton service is, most definitely, not production ready.

I'm on vacation now, but will move this up on my todo list for sure. Basically, all that needs done is to eliminate the state and simply add `User currentUser` to arguments within most methods in the service.

If you don't mind, maybe you can code review the PR before I check it in?

Thanks,
Matthew

**Comment by zirconias** [comment]
someone can explain further more this point ?

**Comment by idrm** [comment]
@MatthewVita: Perhaps, simply making the UserSevice bean session-scoped (or request-scoped) will eliminate the racing condition, though it may have an impact in terms of performance and memory requirements (I'm not terribly familiar with how session/request scoping affects those 2 metrics). Another option would be changing the given() method to be a factory method that returns a UserContextService instance (UserContextService  being a class that encompasses all the chaining methods from UserServie which work with 'currentUser') instance with the specified user context. I hope my word salad made sense...

BTW, thanks for providing code with such extensive architectural/practical coverage.

@zirconias - The singleton scoping of the UserService bean (the default behavior for Spring beans) means that if 2 different threads from 2 different users' requests call that bean's given() method one after another, then the first one to call it will later see the other thread's user context (since the bean is stateful with respect to the currentUser property). Switching to a session or a request scope should eliminate this issue since the 2 threads would work with their own instance of UserService.

**Comment by MatthewVita** [comment]
@idrm:

I decided against making the `UserService` session-scoped because it seems like an anti-pattern. I opted for a solution similar to what you were saying with "factory method that returns a `UserContextService`"... however, instead of a `UserContext` it just returns a plain old `User` model. Seems elegant enough.

I am glad this repository has been helpful to you and and can't thank you enough for helping to improve it. Here is my solution for the race condition: https://github.com/MatthewVita/spring-boot-private-chat/pull/4

I have added you as a collaborator so you can merge it in after a review (please let me know if you see anything off with it).

@zirconias: what idrm said. Best to treat singletons as... well singletons. :)

**Comment by MatthewVita** [comment]
note that I just merged in #4 because I want to get #6

**Comment by MatthewVita** [comment]
Still open for a after-the-fact review, however :)
