### ISSUE TITLE
can't run home page

### ISSUE THREAD

**Issue by jhcao23** [MatthewVita/spring-boot-private-chat#7]
mvn starts successfully but when I open browser with `localhost:8080` the home page only shows "Error. Contact your administrator". Does any one know why?

**Comment by MatthewVita** [comment]
Hi @jhcao23,

Hope you are well.

This error is most likely because Spring can't serve up the resources. You need to `cd` in `src/main/resources/` and run `npm install && gulp` to get those resources shuttled over.

If you're using a Debian-style Linux, you can install npm and gulp via:

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g gulp
```

If you're on Mac, I believe `brew` has a similar approach with installation.

Please let me know if you need any more assistance and let me know what you think of the project. You're more than welcome to tackle any of the TODO items and submit a PR.

Thanks,
Matthew

**Comment by MatthewVi** [comment]
@palashjain888 Did you complete the frontend build process?
